deployment:
  bind9:
    image:
      repository: ubuntu/bind9
      tag: edge
  replicas: 1

kubernetesClusterDomain: cluster.local

serviceAccount:
  create: true
  name: "bind9"

service:
  ports:
    - name: bind9tcp
      nodePort: 30053
      port: 53
      protocol: TCP
      targetPort: bind9tcp
    - name: bind9udp
      nodePort: 30053
      port: 53
      protocol: UDP
      targetPort: bind9udp
  type: NodePort


configs:
  namedConfGlob: "configs/*.conf*"
  zonesGlob: "configs/zones/*"