apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bind9.fullname" . }}-configs
  labels:
  {{- include "bind9.labels" . | nindent 4 }}
data:
{{ (.Files.Glob .Values.configs.namedConfGlob).AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bind9.fullname" . }}-zones
  labels:
  {{- include "bind9.labels" . | nindent 4 }}
data:
{{ (.Files.Glob .Values.configs.zonesGlob).AsConfig | indent 2 }}
