apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bind9.fullname" . }}-configs
  labels:
  {{- include "bind9.labels" . | nindent 4 }}
data:
  named.conf: {{ .Values.configs.namedConf | quote }}
  named.conf.acl: {{ .Values.configs.namedConfAcl | quote }}
  named.conf.local: {{ .Values.configs.namedConfLocal | quote }}
  named.conf.options: {{ .Values.configs.namedConfOptions | quote }}