apiVersion: v1
kind: Service
metadata:
  name: {{ include "bind9.fullname" . }}-service
  labels:
    app: bind9
  {{- include "bind9.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: bind9
  {{- include "bind9.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}