name: Deploy Helm Chart

on:
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Save Kube Config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube/
          echo "${KUBECONFIG}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy app
        run: helm upgrade -f values.yaml bind9 .
